# install zookeeper

- name: add 'zk' group
  group:
    name: zk
    state: present
  become: true

- name: add 'zk' user
  user:
    name: zk
    comment: zookeeper user
    group: zk
    shell: /bin/bash
    state: present
  become: true


- name: add zk to sudoers group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%zk'
    line: '%zk ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true

- name: create zookeeper data directory
  file:
    path: /data/zookeeper
    state: directory
    owner: zk
    group: zk
  become: true

### TODO:
### - disable ssh for zk user
### - disable root login for zk user
### - restart sshd once doing the above

- name: download zookeeper
  get_url:
    url: "{{ zk_download_url }}"
    dest: /opt
  become: true

- name: unpack zookeeper
  unarchive:
    src: "/opt/zookeeper-{{ zk_version }}.tar.gz"
    dest: /opt
    remote_src: true
    group: zk
    owner: zk
    extra_opts:
      - --transform
      - 's/zookeeper-{{ zk_version }}/zookeeper/'
  become: true

- name: configure zookeeper
  template: src=zookeeper.cfg dest="{{ zk_config_path }}"
  become: true

- name: setup systemd target for zookeeper
  template: src=zookeeper.service dest=/etc/systemd/system
  become: true
  notify:
    - restart zookeeper